services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_container
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      - POSTGRES_USER=xalo
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=products
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
